[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200

; CONFIG_PM_ENABLE=1 es necesario para que esp_pm_lock_create/acquire/release
; compilen correctamente y no sean stubs vacíos en el framework de Arduino ESP32.
build_flags =
    -DCONFIG_PM_ENABLE=1

lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.8